<#
.SYNOPSIS
    Bakes a pool (poolers + picks) into data/pool.js so the published site can
    show it to everyone.

.DESCRIPTION
    Picks normally live in one browser's localStorage, which is fine while you
    are drafting and useless once the site is on the web: every visitor would
    arrive to an empty pool. This writes the pool out as a script the pages
    load, the same trick the player data uses.

    The file carries a "published" timestamp. A browser adopts the published
    pool when it has nothing saved, or when that stamp changes -- so poolers
    who once clicked around the draft page still get your next update.

    Feed it a pool file exported from the site (Export JSON), or any file in
    the same shape.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File Y:\HockeyPool\publish-pool.ps1 -PoolFile Pool20252026-import.json
#>

[CmdletBinding()]
param(
    [string] $PoolFile = '',
    [string] $OutPath  = '',
    [string] $Label    = ''      # shown in the header; defaults to today's date
)

$ErrorActionPreference = 'Stop'

$root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if ([string]::IsNullOrWhiteSpace($root)) { $root = (Get-Location).Path }
if ([string]::IsNullOrWhiteSpace($OutPath)) { $OutPath = Join-Path $root 'data\pool.js' }
if ([string]::IsNullOrWhiteSpace($Label))   { $Label   = Get-Date -Format 'yyyy-MM-dd HH:mm' }

if ([string]::IsNullOrWhiteSpace($PoolFile)) { throw 'Pass -PoolFile: the JSON exported from the site.' }
if (-not [System.IO.Path]::IsPathRooted($PoolFile)) { $PoolFile = Join-Path $root $PoolFile }
if (-not (Test-Path $PoolFile)) { throw "Cannot find $PoolFile" }

$pool = [System.IO.File]::ReadAllText($PoolFile, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
if (-not $pool.poolers) { throw "$PoolFile does not look like a pool export (no 'poolers')." }

# ---- check it against the player data before publishing it ------------------
$playersPath = Join-Path $root 'data\players.js'
$known = @{}
if (Test-Path $playersPath) {
    $txt = [System.IO.File]::ReadAllText($playersPath, [System.Text.Encoding]::UTF8)
    $data = [regex]::Match($txt, '(?s)window\.NHL_DATA\s*=\s*(\{.*\});').Groups[1].Value | ConvertFrom-Json
    foreach ($p in $data.players) { $known[[int]$p.i] = $p }
}

$owner = @{}
$warnings = @()
foreach ($pl in $pool.poolers) {
    $filled = @($pl.picks | Where-Object { $null -ne $_ })
    if ($filled.Count -lt 12) { $warnings += "$($pl.name) has only $($filled.Count) of 12 picks" }

    $dCount = 0
    foreach ($id in $filled) {
        if ($owner.ContainsKey([int]$id)) {
            throw "Player id $id is on two rosters: $($owner[[int]$id]) and $($pl.name). Fix that before publishing."
        }
        $owner[[int]$id] = $pl.name

        if ($known.Count -gt 0) {
            $p = $known[[int]$id]
            if ($null -eq $p) { $warnings += "$($pl.name): player id $id is not in data/players.js" }
            elseif ($p.p -eq 'D') { $dCount++ }
        }
    }
    if ($known.Count -gt 0 -and $dCount -eq 0) { $warnings += "$($pl.name) has no defenseman -- cannot be scored legally" }
}

foreach ($w in $warnings) { Write-Warning $w }

# ---- write ------------------------------------------------------------------
$payload = [ordered]@{
    published  = $Label
    version    = 2
    rosterSize = 12
    poolers    = @($pool.poolers | ForEach-Object {
        [ordered]@{ id = [string]$_.id; name = [string]$_.name; picks = @($_.picks) }
    })
}

$json = $payload | ConvertTo-Json -Depth 6 -Compress
if ($json -match '"Count":\s*\d+') { throw 'Arrays serialized as PSObject wrappers -- refusing to write.' }

$outDir = Split-Path -Parent $OutPath
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
$js = "/* Generated by publish-pool.ps1 -- the pool as shown to everyone. */`r`nwindow.POOL_DATA = $json;`r`n"
[System.IO.File]::WriteAllText($OutPath, $js, (New-Object System.Text.UTF8Encoding $false))

Write-Host ''
Write-Host ("Published {0} poolers, {1} picks -> {2}" -f $payload.poolers.Count, $owner.Count, $OutPath) -ForegroundColor Green
Write-Host "  stamp: $Label"
Write-Host '  commit and push to put it on the web.' -ForegroundColor DarkGray
