<#
.SYNOPSIS
    Runs the self-test suites against the site's pages in headless Chrome.

.DESCRIPTION
    For each page/suite pair, builds a throwaway copy of the page with the
    tests injected, loads it in headless Chrome, scrapes the results out of the
    rendered DOM, then deletes the copy. The real pages are never modified.

    The copies are written next to the originals on purpose: the pages load
    assets/ and data/ with relative paths, so a copy elsewhere would come up
    with no player data.

    Exits 1 if any check fails, so it can gate a change.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File Y:\HockeyPool\run-selftest.ps1
#>

[CmdletBinding()]
param([string] $ChromePath = '')

$ErrorActionPreference = 'Stop'

$root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if ([string]::IsNullOrWhiteSpace($root)) { $root = (Get-Location).Path }

$suites = @(
    @{ Name = 'Draft page';     Page = 'pool.html';      Test = '_selftest.js' },
    @{ Name = 'Standings page'; Page = 'standings.html'; Test = '_selftest-standings.js' },
    @{ Name = 'Fun facts page'; Page = 'funfacts.html';  Test = '_selftest-funfacts.js' }
)

foreach ($s in $suites) {
    foreach ($f in (Join-Path $root $s.Page), (Join-Path $root $s.Test)) {
        if (-not (Test-Path $f)) { throw "Missing $f" }
    }
}

# ---- locate a browser ----
if ([string]::IsNullOrWhiteSpace($ChromePath)) {
    $candidates = @(
        "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
        "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
        "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe",
        "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe",
        "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"
    )
    $ChromePath = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $ChromePath) { throw 'No Chrome or Edge found. Pass -ChromePath explicitly.' }

$failed = 0

# -----------------------------------------------------------------------------
# Navigation: every page must link to every other one, and every local link must
# point at a file that exists. The record book is generated by build-report.py
# and has no browser suite of its own, so this is what keeps it wired in.
# -----------------------------------------------------------------------------
Write-Host ''
Write-Host '=== Navigation ===' -ForegroundColor Cyan

$pages = 'pool.html', 'standings.html', 'funfacts.html', 'pool-records.html'
# index.html is the published site's landing page: it only has to point at
# pages that exist, not link to all of them.
$linkOnly = @('index.html')
$navFails = 0

foreach ($page in ($pages + $linkOnly)) {
    $path = Join-Path $root $page
    if (-not (Test-Path $path)) {
        Write-Host "FAIL missing page $page" -ForegroundColor Red
        $navFails++
        continue
    }
    $text = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

    # Links to the other three, plus a marker for the page you are on.
    foreach ($target in $pages) {
        if ($target -eq $page -or $linkOnly -contains $page) { continue }
        if ($text -notmatch [regex]::Escape("href=""$target""")) {
            Write-Host "FAIL $page does not link to $target" -ForegroundColor Red
            $navFails++
        }
    }

    # Every local .html link must resolve to a real file.
    foreach ($m in [regex]::Matches($text, 'href="([^"#?:]+\.html)"')) {
        $target = $m.Groups[1].Value
        if (-not (Test-Path (Join-Path $root $target))) {
            Write-Host "FAIL $page links to missing file $target" -ForegroundColor Red
            $navFails++
        }
    }
}

if ($navFails -eq 0) {
    Write-Host ("PASS all {0} pages link to each other and every link resolves (index.html included)" -f $pages.Count) -ForegroundColor Green
} else {
    $failed++
}

# The record book is generated; hand-edits to it get wiped by the next build.
$tpl = Join-Path $root 'pool-records.template.html'
if (Test-Path $tpl) {
    $tplText = [System.IO.File]::ReadAllText($tpl, [System.Text.Encoding]::UTF8)
    if ($tplText -notmatch 'href="standings\.html"') {
        Write-Host 'FAIL pool-records.template.html has no nav — a rebuild would drop it from the site' -ForegroundColor Red
        $failed++
    } else {
        Write-Host 'PASS the record book template carries the nav, so rebuilds keep it' -ForegroundColor Green
    }
}

foreach ($s in $suites) {
    Write-Host ''
    Write-Host "=== $($s.Name) ($($s.Page)) ===" -ForegroundColor Cyan

    $htmlPath = Join-Path $root $s.Page
    $testPath = Join-Path $root $s.Test
    $tempHtml = Join-Path $root ('_test_' + $s.Page)

    $html = [System.IO.File]::ReadAllText($htmlPath, [System.Text.Encoding]::UTF8)
    $test = [System.IO.File]::ReadAllText($testPath, [System.Text.Encoding]::UTF8)

    # Split the closing tag so this script's own source can't be mistaken for it.
    $inject = "<script>`r`n$test`r`n</" + "script>`r`n</body>"
    $built  = [regex]::Replace($html, '</body>',
                [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $inject }, 1)
    [System.IO.File]::WriteAllText($tempHtml, $built, (New-Object System.Text.UTF8Encoding $false))

    $profileDir = Join-Path $env:TEMP "poolselftest_$(Get-Random)"
    $outFile    = Join-Path $env:TEMP "poolselftest_out_$PID.txt"
    $errFile    = Join-Path $env:TEMP "poolselftest_err_$PID.txt"

    $fileUrl = 'file:///' + ($tempHtml -replace '\\', '/')

    try {
        Start-Process -FilePath $ChromePath -Wait -NoNewWindow `
            -RedirectStandardOutput $outFile -RedirectStandardError $errFile `
            -ArgumentList @(
                '--headless=new', '--disable-gpu', '--no-sandbox',
                '--allow-file-access-from-files', "--user-data-dir=$profileDir",
                '--virtual-time-budget=8000', '--dump-dom', $fileUrl
            ) | Out-Null

        $dom = [System.IO.File]::ReadAllText($outFile, [System.Text.Encoding]::UTF8)
        $m   = [regex]::Match($dom, '(?s)<div id="TESTOUT">(.*?)</div>')

        if (-not $m.Success) {
            Write-Host 'Self-test produced no output — the page probably threw before the harness ran.' -ForegroundColor Red
            $failed++
            continue
        }

        $results = [System.Net.WebUtility]::HtmlDecode($m.Groups[1].Value)

        foreach ($line in ($results -split "`n")) {
            if ($line -match '^\s*$') { continue }
            $colour = if ($line -match '^FAIL')        { 'Red' }
                      elseif ($line -match '^PASS')    { 'Green' }
                      elseif ($line -match 'ALL TESTS PASSED') { 'Green' }
                      elseif ($line -match 'FAILURE')  { 'Red' }
                      else                             { 'DarkGray' }
            Write-Host $line -ForegroundColor $colour
        }

        if ($results -match 'FAILURE\(S\)' -or $results -match '(?m)^FAIL') { $failed++ }
    }
    finally {
        Remove-Item $tempHtml, $outFile, $errFile -Force -ErrorAction SilentlyContinue
        Remove-Item $profileDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-Host ''
if ($failed) {
    Write-Host "$failed of $($suites.Count) suites FAILED." -ForegroundColor Red
    exit 1
}
Write-Host "All $($suites.Count) suites passed." -ForegroundColor Green
exit 0
